name: "Test Default Token List"
on:
  push:
    branches:
      - master
    paths:
      - "lists/token-lists/default-token-list/tokens/**"
  pull_request:
    paths:
      - "lists/token-lists/default-token-list/tokens/**"
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
        working-directory: './lists/token-lists/default-token-list'
      - run: pnpm run test
        working-directory: './lists/token-lists/default-token-list'