name: "Test Token Logos"
on:
  push:
    branches:
      - master
    # paths:
    #   - "logos/token-logos/token/**"
  pull_request:
    branches:
      - master
    # paths:
    #   - "logos/token-logos/token/**"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies and test
        run: pnpm install && pnpm test
        working-directory: './logos/token-logos'